### PR TITLE
fix: mechanisms/memif should not duplicate preference mechanisms

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>

Closes https://github.com/networkservicemesh/sdk/issues/721

### CODE REVIEW

**Comment by edwarnicke** [comment]
@denis-tingaikin This seems to have hit some sort of issue on license header changes...

**Comment by edwarnicke** [comment]
@denis-tingaikin Just fixing the license headers isn't really the issue here... the real question is: why is CI failing on license headers that are not part of the PR?

**Comment by denis-tingaikin** [comment]
@edwarnicke 

> Just fixing the license headers isn't really the issue here...

Actually, it is the root cause of ci failing. 

Currently, in the main branch, we have outdated golangci linter version that allows in 2021 to do changes in files from 2020.

When I updated the version of linter, all files that have updated this year became invalid.

**Comment by edwarnicke** [comment]
> When I updated the version of linter, all files that have updated this year became invalid.
Ah... I see :)

**Pull request merged**
