### PR TITLE
Add wireguard mechanism

### PR DESCRIPTION
**Pull request by glazychev-art**
#66 

Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

### CODE REVIEW

**Review by denis-tingaikin — APPROVED** [review]
LGTM

**Comment by edwarnicke** [comment]
Wireguard also needs an analog to:
https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/mechanisms/vxlan/client.go#L54

I *think* based on [this](https://lists.zx2c4.com/pipermail/wireguard/2017-December/002201.html) that the proper amount to subtract from MTU for wireguard is 80 bytes.

**Comment by denis-tingaikin** [comment]
@edwarnicke Is it fixed by https://github.com/networkservicemesh/api/pull/99 + https://github.com/networkservicemesh/sdk-vpp/pull/124/commits/b17fd25b5ffb96fe67d304d997ece4b0c45b59bc?

**Comment by edwarnicke** [comment]
@glazychev-art 

Some notes...

1.  I've merged https://github.com/edwarnicke/govpp/pull/25 so that should be the operative container now
2. I figured out what it was taking 5 seconds for the interfaces to come up, and have a fix: https://github.com/networkservicemesh/sdk-vpp/pull/265
3. To adapt to this fix, peer.NewServer() will need to set its parameters for the mechanism on the downward pass through the call chain, and take its action to configure the wireguard in VPP on the return pass.

**Pull request merged**
