### PR TITLE
Move some generic functions from internal/vppinit to sdk-vpp

### PR DESCRIPTION
**Pull request by ljkiraly**
This solves the issue: cmd-forwarder-vpp#355

Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>

### CODE REVIEW

**Comment by edwarnicke** [comment]
@ljkiraly Could you tell me a bit about what you are looking to do with these functions?

The reason I ask is not because I have any intrinsic objection to moving functionality like this upstream... I'm all for that...

But one of the reasons I had then in internal/ is because *the way* they were written was overly specific to what I was doing in cmd-forwarder-vpp... and so we probably want to clean them up to be actually, you know, good :)  But 'good' is going to depend a lot on 'good for what' :)

**Comment by ljkiraly** [comment]
@edwarnicke All these functions should be used by vpp forwarder to set up a new veth pair to a specified interface. The NSE which supports the remote vlan mechanism should specify an interface to be used, other than the default - specified by forwarder config (TUNNEL_IP) or by default route. 
This interface does not need to have an IP address or routes configured for it's IP address.

**Comment by edwarnicke** [comment]
> All these functions should be used by vpp forwarder to set up a new veth pair to a specified interface.

**Comment by ljkiraly** [comment]
@edwarnicke Yes, it's related to vlan multiplexing, but the remote vlan mechanism case.
I created an issue vlan-forwarder#358 to summarize the belonging PRs.

**Pull request closed without merging**
