### PR TITLE
Add an option to expose Prometheus metrics via http/s server

### PR DESCRIPTION
**Pull request by bszirtes**
## Description

Initialized Prometheus metric types and expanded current metrics to push values into Prometheus too, if enabled.

## Issue link

https://github.com/networkservicemesh/sdk/issues/1652

## How Has This Been Tested?

- [ ] Added unit testing to cover
- [X] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [ ] Bug fix
- [X] New functionality
- [ ] Documentation
- [ ] Refactoring
- [ ] CI

### CODE REVIEW

**Review by denis-tingaikin — APPROVED** [review]
LGTM.

Could you fix linter?

**Comment by bszirtes** [comment]
Hi @denis-tingaikin,

Thank you for the feedback! Regarding the linter issue, do you have any recommendations on where to initialize the Prometheus metric types? I'm considering moving the content of my `init` function (since that's causing the linting issue) into a new function and calling it directly from the forwarder. Would that be a better approach?

**Comment by denis-tingaikin** [comment]
I think we can define static sync.Once in the stats/prometheus and do initialization in the NewServer function if promeheus enabled.

**Comment by bszirtes** [comment]
May I ask which specific NewServer function you are referring to @denis-tingaikin?

**Comment by denis-tingaikin** [comment]
Sure, I'd try something like this:

in the `prometheus.go`
```diff
package stats

+ import "sync"

+ var prometheusInitOnce sync.Once

-  func init() {
+ func registerMetrics() {
+   if !prometheus.Enabled() {
+     return  
+   }
  ...
}
```

Then we could initiate it in the stats client/server https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/metrics/stats/server.go#L44, https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/metrics/stats/client.go#L46

via adding one line
```go
prometheusInitOnce.Do(registerMetrics)
```

**Comment by bszirtes** [comment]
Hi @denis-tingaikin,

Thank you for the clarification! I've made the changes as you recommended.

**Pull request merged**
